// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjjcceqkdvjpibuxuvzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqamNjZXFrZHZqcGlidXh1dnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMjIzNTcsImV4cCI6MjA3MjY5ODM1N30.G_RSrYNBaxLF68x_oiLv9Q0Jf6ctVKrBHm-9ZQYOQ04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});